# prek compatible configuration
# See https://pre-commit.com for more information
repos:
  - repo: https://gitcode.com/gh_mirrors/ru/ruff-pre-commit.git
    # Ruff version - keep in sync with pyproject.toml
    rev: v0.15.4
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://gitcode.com/gh_mirrors/pr/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
