[tox]
envlist = py38, py39, py310, py311, py312, py313
min_version = 4.0
requires = tox-uv
skipsdist = true

[testenv]
uv_sync = true
deps =
    .
    .[tox]
commands =
    pytest -m "not slow" -n 2 --dist=loadfile {posargs}
passenv = *
setenv =
    PYTHONPATH = {toxinidir}/src
    PYTHONDONTWRITEBYTECODE = 1
    QT_QPA_PLATFORM = offscreen
